# Stabilize AnimOrg Backend and Migrate Frontend Task List

- [x] Phase 1: Backend Stabilization
  - [x] Investigate and fix sfw=true cache miss root cause
  - [x] Implement robust exponential backoff retries with jitter and Retry-After support
  - [x] Refactor HomeService to use Promise.allSettled and staggering to prevent 429 rate limit triggers
  - [x] Optimize JikanProvider to clean default query parameters and slice arrays locally to maximize cache hit rates
- [x] Phase 2 & 3: Remove Frontend Direct Jikan Usage & Centralized API Client
  - [x] Search the frontend for direct Jikan references (api.jikan.moe)
  - [x] Ensure a centralized backend client handles development / production environments dynamically (EXPO_PUBLIC_API_URL and hostUri)
  - [x] Refactor all frontend Jikan adapters to route exclusively through the backend proxy client
- [x] Phase 4: Backend Endpoint Coverage
  - [x] Review all frontend Jikan/AniList integrations (e.g. relations, anime by genre, characters search, etc.)
  - [x] Implement any missing backend endpoints to ensure 100% backend API coverage
- [x] Phase 7-9: Testing, Cleanup, and Code Validation
  - [x] Terminate/delete obsolete scrapers, mock services, and unused files
  - [x] Verify TypeScript and build checks compile cleanly, with no errors
- [x] Phase 10: Debug Search Page Results Failure
  - [x] Apply AniList GraphQL query signature dynamic generation fix in AniListAdapter.ts
  - [x] Strip score/rank sorting from JikanProvider.ts search params to resolve 504 timeouts
  - [x] Verify search queries succeed end-to-end
- [x] Phase 11: Production Audit of Backend and Caching System
  - [x] Audit cache.ts and cacheWarmJob.ts for robustness and potential memory/logical issues
  - [x] Audit server and controller error boundaries and performance
  - [x] Create audit report and implement any necessary optimizations
