export const XP_VALUES = {
    DAILY_LOGIN: 2,
    ADD_TO_WATCHLIST: 5,
    START_TRACKING: 10,
    EPISODE_WATCHED: 3,
    COMPLETE_ANIME: 25,
    RATE_ANIME: 8,
    FINISH_SEASON: 15,
    COMPLETE_FIRST_ANIME: 50,
    STREAK_7_DAY: 40,
    STREAK_30_DAY: 200,
    DISCOVER_GENRE: 10,
    USE_SEARCH: 1,
    OPEN_DETAILS: 1,
};

export const XP_CAPS = {
    USE_SEARCH_DAILY_MAX: 5,
    OPEN_DETAILS_DAILY_MAX: 20,
};
